import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Website",
  description: "Generated by create next app",
  // to generate static open graph images
  openGraph: {
    title: "Our website",
    description: "Created with next.js",
    images: [{
      url:"/global.svg",
      height:600,
      width:800,
      alt:"Logo"
    }], // we can use more then one image
    url: "http://localhost:3000",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
